//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Web.Export {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MimeType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MimeType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Web.Export.MimeType", typeof(MimeType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/bmp.
        /// </summary>
        public static string Bmp {
            get {
                return ResourceManager.GetString("Bmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/msword.
        /// </summary>
        public static string Doc {
            get {
                return ResourceManager.GetString("Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-word.document.macroEnabled.12.
        /// </summary>
        public static string Docm {
            get {
                return ResourceManager.GetString("Docm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.wordprocessingml.document.
        /// </summary>
        public static string Docx {
            get {
                return ResourceManager.GetString("Docx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/msword.
        /// </summary>
        public static string Dot {
            get {
                return ResourceManager.GetString("Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-word.template.macroEnabled.12.
        /// </summary>
        public static string Dotm {
            get {
                return ResourceManager.GetString("Dotm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.wordprocessingml.template.
        /// </summary>
        public static string Dotx {
            get {
                return ResourceManager.GetString("Dotx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/gif.
        /// </summary>
        public static string Gif {
            get {
                return ResourceManager.GetString("Gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/html.
        /// </summary>
        public static string Html {
            get {
                return ResourceManager.GetString("Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/jpeg.
        /// </summary>
        public static string Jpeg {
            get {
                return ResourceManager.GetString("Jpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/octet-stream.
        /// </summary>
        public static string NoConocido {
            get {
                return ResourceManager.GetString("NoConocido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/pdf.
        /// </summary>
        public static string Pdf {
            get {
                return ResourceManager.GetString("Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-powerpoint.
        /// </summary>
        public static string Pot {
            get {
                return ResourceManager.GetString("Pot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-powerpoint.template.macroEnabled.12.
        /// </summary>
        public static string Potm {
            get {
                return ResourceManager.GetString("Potm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.presentationml.template.
        /// </summary>
        public static string Potx {
            get {
                return ResourceManager.GetString("Potx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-powerpoint.
        /// </summary>
        public static string Ppa {
            get {
                return ResourceManager.GetString("Ppa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-powerpoint.addin.macroEnabled.12.
        /// </summary>
        public static string Ppam {
            get {
                return ResourceManager.GetString("Ppam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-powerpoint.
        /// </summary>
        public static string Pps {
            get {
                return ResourceManager.GetString("Pps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-powerpoint.slideshow.macroEnabled.12.
        /// </summary>
        public static string Ppsm {
            get {
                return ResourceManager.GetString("Ppsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.presentationml.slideshow.
        /// </summary>
        public static string Ppsx {
            get {
                return ResourceManager.GetString("Ppsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-powerpoint.
        /// </summary>
        public static string Ppt {
            get {
                return ResourceManager.GetString("Ppt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-powerpoint.presentation.macroEnabled.12.
        /// </summary>
        public static string Pptm {
            get {
                return ResourceManager.GetString("Pptm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.presentationml.presentation.
        /// </summary>
        public static string Pptx {
            get {
                return ResourceManager.GetString("Pptx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/tiff.
        /// </summary>
        public static string Tif {
            get {
                return ResourceManager.GetString("Tif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/plain.
        /// </summary>
        public static string Txt {
            get {
                return ResourceManager.GetString("Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-excel.
        /// </summary>
        public static string Xla {
            get {
                return ResourceManager.GetString("Xla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-excel.addin.macroEnabled.12.
        /// </summary>
        public static string Xlam {
            get {
                return ResourceManager.GetString("Xlam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-excel.
        /// </summary>
        public static string Xls {
            get {
                return ResourceManager.GetString("Xls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-excel.sheet.binary.macroEnabled.12.
        /// </summary>
        public static string Xlsb {
            get {
                return ResourceManager.GetString("Xlsb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-excel.sheet.macroEnabled.12.
        /// </summary>
        public static string Xlsm {
            get {
                return ResourceManager.GetString("Xlsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-excel.template.macroEnabled.12.
        /// </summary>
        public static string Xltm {
            get {
                return ResourceManager.GetString("Xltm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.spreadsheetml.template.
        /// </summary>
        public static string Xltx {
            get {
                return ResourceManager.GetString("Xltx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-excel.
        /// </summary>
        public static string Xslt {
            get {
                return ResourceManager.GetString("Xslt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.
        /// </summary>
        public static string Xslx {
            get {
                return ResourceManager.GetString("Xslx", resourceCulture);
            }
        }
    }
}
