//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Implementacion.Wcf.Error.Proxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorServicioRespuesta", Namespace="http://schemas.datacontract.org/2004/07/Framework.Wcf.Error")]
    [System.SerializableAttribute()]
    public partial class ErrorServicioRespuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Implementacion.Wcf.Error.Proxy.TipoErrorServicio TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Implementacion.Wcf.Error.Proxy.TipoErrorServicio Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoErrorServicio", Namespace="http://schemas.datacontract.org/2004/07/Framework.Wcf.Error")]
    public enum TipoErrorServicio : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorNoManejado = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorBaseDatos = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorActualizacionBaseDatos = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorEliminacionBaseDatos = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorTiempoConexion = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorNegocio = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorComunicacion = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorValidacion = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Implementacion.Wcf")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.IServicio")]
    public interface IServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetData", ReplyAction="http://tempuri.org/IServicio/GetDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Implementacion.Wcf.Error.Proxy.ErrorServicioRespuesta), Action="http://tempuri.org/IServicio/GetDataErrorServicioRespuestaFault", Name="ErrorServicioRespuesta", Namespace="http://schemas.datacontract.org/2004/07/Framework.Wcf.Error")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServicio/GetDataUsingDataContractResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Implementacion.Wcf.Error.Proxy.ErrorServicioRespuesta), Action="http://tempuri.org/IServicio/GetDataUsingDataContractErrorServicioRespuestaFault", Name="ErrorServicioRespuesta", Namespace="http://schemas.datacontract.org/2004/07/Framework.Wcf.Error")]
        Implementacion.Wcf.Error.Proxy.CompositeType GetDataUsingDataContract(Implementacion.Wcf.Error.Proxy.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetDataErrorValidacion", ReplyAction="http://tempuri.org/IServicio/GetDataErrorValidacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Implementacion.Wcf.Error.Proxy.ErrorServicioRespuesta), Action="http://tempuri.org/IServicio/GetDataErrorValidacionErrorServicioRespuestaFault", Name="ErrorServicioRespuesta", Namespace="http://schemas.datacontract.org/2004/07/Framework.Wcf.Error")]
        string GetDataErrorValidacion(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetDataErrorRegla", ReplyAction="http://tempuri.org/IServicio/GetDataErrorReglaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Implementacion.Wcf.Error.Proxy.ErrorServicioRespuesta), Action="http://tempuri.org/IServicio/GetDataErrorReglaErrorServicioRespuestaFault", Name="ErrorServicioRespuesta", Namespace="http://schemas.datacontract.org/2004/07/Framework.Wcf.Error")]
        string GetDataErrorRegla(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChannel : Implementacion.Wcf.Error.Proxy.IServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClient : System.ServiceModel.ClientBase<Implementacion.Wcf.Error.Proxy.IServicio>, Implementacion.Wcf.Error.Proxy.IServicio {
        
        public ServicioClient() {
        }
        
        public ServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public Implementacion.Wcf.Error.Proxy.CompositeType GetDataUsingDataContract(Implementacion.Wcf.Error.Proxy.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public string GetDataErrorValidacion(int value) {
            return base.Channel.GetDataErrorValidacion(value);
        }
        
        public string GetDataErrorRegla(int value) {
            return base.Channel.GetDataErrorRegla(value);
        }
    }
}
