//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Implementacion.Validacion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Implementacion.Validacion.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FirstName is a mandatory Field.
        /// </summary>
        internal static string Cliente_FirstName_The_FirstName_is_a_mandatory_Field {
            get {
                return ResourceManager.GetString("Cliente_FirstName_The_FirstName_is_a_mandatory_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FirstName should be greater than 10 characters..
        /// </summary>
        internal static string Cliente_FirstName_The_FirstName_should_be_greater_than_10_characters_ {
            get {
                return ResourceManager.GetString("Cliente_FirstName_The_FirstName_should_be_greater_than_10_characters_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LastName is a mandatory Field.
        /// </summary>
        internal static string Cliente_LastName_The_LastName_is_a_mandatory_Field {
            get {
                return ResourceManager.GetString("Cliente_LastName_The_LastName_is_a_mandatory_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LastName should be greater than 10 characters..
        /// </summary>
        internal static string Cliente_LastName_The_LastName_should_be_greater_than_10_characters_ {
            get {
                return ResourceManager.GetString("Cliente_LastName_The_LastName_should_be_greater_than_10_characters_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Title is a mandatory Field.
        /// </summary>
        internal static string Cliente_Title_The_Title_is_a_mandatory_Field {
            get {
                return ResourceManager.GetString("Cliente_Title_The_Title_is_a_mandatory_Field", resourceCulture);
            }
        }
    }
}
